// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFX_1Fu6zJfzopheXa4G4h8FK_xQ_Kl6k',
    appId: '1:317505792527:web:7c8fe6211d5b2f295ad17a',
    messagingSenderId: '317505792527',
    projectId: 'filesharing-proj',
    authDomain: 'filesharing-proj.firebaseapp.com',
    storageBucket: 'filesharing-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTEz84O8-YMsSSXQEqlBpjSM5vdrQmgk',
    appId: '1:317505792527:android:084d1c5424d8e64a5ad17a',
    messagingSenderId: '317505792527',
    projectId: 'filesharing-proj',
    storageBucket: 'filesharing-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeC-WWr20e_DbfaTkRHCfCzabPPHODJs',
    appId: '1:317505792527:ios:085c9ada7d6a27ef5ad17a',
    messagingSenderId: '317505792527',
    projectId: 'filesharing-proj',
    storageBucket: 'filesharing-proj.appspot.com',
    iosClientId: '317505792527-0s6n6l3e2ar8jpsgnapimvcni63tq210.apps.googleusercontent.com',
    iosBundleId: 'app.mdev.fileshare',
  );
}
